version: 0.2

phases:
  install:
   runtime-versions:
    nodejs: 24
   commands:
    - echo Installing source NPM dependencies...
    - npm install
  build:
   commands:
    - echo Build started on 'date'
    - echo Building the Node.js application...
    - npm run build
  post_build:
   commands:
    - echo Build completed on 'date'
    - mkdir deploy
    - cp -r dist deploy/dist
    - cp appspec.yml deploy/
    - cp -r scripts deploy/
    - chmod +x deploy/scripts/restartNginx.sh
    - chmod +x deploy/scripts/appStop.sh

artifacts:
  files:
   - '**/*'
  base-directory: deploy
  name: frontend-build       