#single stage docker file
FROM node:24.15 AS builder
WORKDIR /app
RUN cd ..
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
RUN cd ..

COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 
